version: '2'
services:
  agentui:
    image: indigoframework/agent-ui:0.2.0
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "4000:4000"
  agent:
    build:
      dockerfile: Dockerfile.dev
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
    ports:
    - "3000:3000"
  store:
    env_file:
    - ./config/dev.env
    - ./config/dev.secret.env
    user: root
    volumes:
    - ./segments:/var/stratumn/filestore
networks:
  default:
    driver: bridge
    driver_opts:
        name: location-tracker_dev
