version: '2'
services:
  agent:
    build:
      context: ./agent
    image: tbast/location-tracker-agent-js
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
    volumes:
    - ./agent:/src/server
    - ./proof-of-location:/var/stratumn/zkp
    depends_on:
    - store
  store:
    image: indigoframework/filestore:0.2.0
    env_file:
    - ./config/common.env
    - ./config/common.secret.env
